version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: posql
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: kclk
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/mydb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: secret
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    command: start-dev
    restart: unless-stopped

volumes:
  postgres_data: