spring.application.name=backend
spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:secret}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/ITResurceManager
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/ITResurceManager/protocol/openid-connect/certs
# Keycloak Admin API Configuration
keycloak.admin.url=http://localhost:8081
keycloak.realm=ITResurceManager
keycloak.admin.client-id=admin-cli
keycloak.admin.username=admin
keycloak.admin.password=admin
