service:
  type: LoadBalancer

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik

providers:
  kubernetesIngress:
    enabled: true
  kubernetesCRD:
    enabled: true
