apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: dvloper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.0
          args:
            - start-dev
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: dvloper-secrets
                  key: KEYCLOAK_ADMIN_USERNAME
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dvloper-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres-keycloak:5432/keycloak_db
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dvloper-secrets
                  key: KEYCLOAK_DB_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dvloper-secrets
                  key: KEYCLOAK_DB_PASSWORD
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_PROXY
              value: edge
            - name: KC_HOSTNAME
              value: dvloper.local
            - name: KC_HTTP_RELATIVE_PATH
              value: /keycloak
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: dvloper
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
