apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-app-data
  namespace: dvloper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: dvloper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: dvloper-secrets
                  key: APP_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: dvloper-secrets
                  key: APP_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dvloper-secrets
                  key: APP_DB_PASSWORD
          volumeMounts:
            - name: postgres-app-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-app-data
          persistentVolumeClaim:
            claimName: postgres-app-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dvloper
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
