package io.dvloper.backend.entities;

import org.junit.jupiter.api.Test;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;

import java.util.Set;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class CategoryTest {

    private final Validator validator;

    public CategoryTest() {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        validator = factory.getValidator();
    }

    @Test
    void testDefaultConstructor() {
        Category category = new Category();
        assertNotNull(category);
        assertNull(category.getId());
        assertNull(category.getName());
        assertNull(category.getDescription());
    }

    @Test
    void testParameterizedConstructor() {
        Category category = new Category("Laptops", "High performance computers");

        assertNotNull(category);
        assertNull(category.getId()); // ID is generated by database
        assertEquals("Laptops", category.getName());
        assertEquals("High performance computers", category.getDescription());
    }

    @Test
    void testGettersAndSetters() {
        Category category = new Category();
        UUID testId = UUID.randomUUID();

        category.setId(testId);
        category.setName("Monitors");
        category.setDescription("Display devices for computers");

        assertEquals(testId, category.getId());
        assertEquals("Monitors", category.getName());
        assertEquals("Display devices for computers", category.getDescription());
    }

    @Test
    void testValidCategory() {
        Category category = new Category("Laptops", "High performance computers");

        Set<ConstraintViolation<Category>> violations = validator.validate(category);
        assertTrue(violations.isEmpty(), "Valid category should have no violations");
    }

    @Test
    void testNameNotBlank() {
        Category category = new Category("", "Description");

        Set<ConstraintViolation<Category>> violations = validator.validate(category);
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
                .anyMatch(v -> v.getPropertyPath().toString().equals("name")));
    }

    @Test
    void testNameMinLength() {
        Category category = new Category("AB", "Description here");

        Set<ConstraintViolation<Category>> violations = validator.validate(category);
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
                .anyMatch(v -> v.getPropertyPath().toString().equals("name")));
    }

    @Test
    void testNameMaxLength() {
        String longName = "A".repeat(51);
        Category category = new Category(longName, "Description");

        Set<ConstraintViolation<Category>> violations = validator.validate(category);
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
                .anyMatch(v -> v.getPropertyPath().toString().equals("name")));
    }

    @Test
    void testDescriptionNotBlank() {
        Category category = new Category("Name", "");

        Set<ConstraintViolation<Category>> violations = validator.validate(category);
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
                .anyMatch(v -> v.getPropertyPath().toString().equals("description")));
    }

    @Test
    void testDescriptionMinLength() {
        Category category = new Category("Name", "ABC");

        Set<ConstraintViolation<Category>> violations = validator.validate(category);
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
                .anyMatch(v -> v.getPropertyPath().toString().equals("description")));
    }

    @Test
    void testDescriptionMaxLength() {
        String longDesc = "A".repeat(201);
        Category category = new Category("Name", longDesc);

        Set<ConstraintViolation<Category>> violations = validator.validate(category);
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
                .anyMatch(v -> v.getPropertyPath().toString().equals("description")));
    }

    @Test
    void testValidNameBoundary() {
        Category category1 = new Category("ABC", "Valid description");
        Set<ConstraintViolation<Category>> violations1 = validator.validate(category1);
        assertTrue(violations1.isEmpty(), "3 characters should be valid");

        Category category2 = new Category("A".repeat(50), "Valid description");
        Set<ConstraintViolation<Category>> violations2 = validator.validate(category2);
        assertTrue(violations2.isEmpty(), "50 characters should be valid");
    }

    @Test
    void testValidDescriptionBoundary() {
        Category category1 = new Category("Name", "ABCD");
        Set<ConstraintViolation<Category>> violations1 = validator.validate(category1);
        assertTrue(violations1.isEmpty(), "4 characters should be valid");

        Category category2 = new Category("Name", "A".repeat(200));
        Set<ConstraintViolation<Category>> violations2 = validator.validate(category2);
        assertTrue(violations2.isEmpty(), "200 characters should be valid");
    }

    @Test
    void testNullName() {
        Category category = new Category(null, "Description");

        Set<ConstraintViolation<Category>> violations = validator.validate(category);
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
                .anyMatch(v -> v.getPropertyPath().toString().equals("name")));
    }

    @Test
    void testNullDescription() {
        Category category = new Category("Name", null);

        Set<ConstraintViolation<Category>> violations = validator.validate(category);
        assertFalse(violations.isEmpty());
        assertTrue(violations.stream()
                .anyMatch(v -> v.getPropertyPath().toString().equals("description")));
    }
}
